### ISSUE TITLE
Right click harvest bugs

### ISSUE THREAD

**Issue by ProspectPyxis** [coderbot16/SimpleFlax#7]
First of all, thank you for implementing this feature! However, it's still got a few quirks in it that I'm noticing in testing:
1. You can only right click the bottom of the flax - right clicking the top part does nothing.
2. There is some strange behavior with using bone meal on it. Sometimes, even if the plant isn't fully grown yet, it'll get harvested anyways and only drop flax seeds with no string.

**Comment by coderbot16** [comment]
That's extremely weird, because I'm pretty sure I specifically tested both of those things and fixed them...

Will take a look tomorrow.

**Comment by coderbot16** [comment]
The first issue is supposed to be handled by https://github.com/coderbot16/SimpleFlax/blob/master/src/main/java/simpleflax/compat/SimpleHarvestCompat.java#L52-L67, not sure why it doesn't work...

**Comment by coderbot16** [comment]
Alright, I could not reproduce it in my dev environment or in a fresh one with only SimpleHarvest and SimpleFlax. However, it seems that your first issue is almost certainly related to the second: it's harvesting fully grown bottom flax plants without checking that the top plant is grown.

My best guess is that you still have your config changed with the incomplete flax plant support from earlier. This is not needed, SimpleFlax registers itself with SimpleHarvest automatically without any needed configuration. So try removing any reference to SimpleFlax from harvest_config.json and if that doesn't work, delete and regenerate it.

If none of that fixes the issue, deeper investigation will be needed.

**Comment by ProspectPyxis** [comment]
After some testing, I figured out the problem: it was a conflict with harvestcraft's own right click harvest. Disabling that fixed it.

**Comment by coderbot16** [comment]
Ah, that makes sense. I wonder if there’s a way to be compatible with HC by default in that case.

**Comment by coderbot16** [comment]
I tested it and it appears that the latest updates of SimpleFlax and HarvestCraft don't have the issue, so everything is fine here.
